#  -*- coding: utf-8 -*-

* Config helpers
** ensure-installed-and-require

   This function calls =require= on a package, installing it if it's
   not already installed.

#+begin_src emacs-lisp
  (defun ensure-installed-and-require (p)
    (when (not (package-installed-p p))
      (package-install p))
    (require p))
#+end_src

** diminish

   A package to manage how modes appear in the modeline (and, in
   particular, hide boring minor modes we don't care about).  See
   [[magit]] for an example of use.

#+begin_src emacs-lisp
  (ensure-installed-and-require 'diminish)
#+end_src

* Global settings
** better-defaults
  [[https://github.com/technomancy/better-defaults][better-defaults]] does a bunch of generic emacs interface tidying,
  including:
  - better buffer unique names
  - turn off scrollbar, menu bar, toolbar
#+begin_src emacs-lisp
  (ensure-installed-and-require 'better-defaults)
#+end_src

** ido

  ido-ubiquitous enables ido in many places.  (better-defaults already
  enables ido for some things, this just goes further).  smex adds
  ido-like behaviour to =M-x=.
#+begin_src emacs-lisp
  (ensure-installed-and-require 'ido-ubiquitous)
  (ido-mode t)
  (ido-ubiquitous-mode t)

  (ensure-installed-and-require 'smex)
  (setq smex-save-file (concat user-emacs-directory ".smex-items"))
  (smex-initialize)
  (global-set-key (kbd "M-x") 'smex)
#+end_src

** magit

   [[https://github.com/magit/magit][magit]] is the only way to interact with git.  Seriously, even when
   I'm using other editors, I'll keep emacs open in order to use magit.
   The main reasons I like it:
   - easy manipulation of individual lines within a changeset
   - one-character commands for all common operations (push, pull,
     commit, rebase, merge..)
   As a result, I bind a global key combination to =magit-status= so
   it's always easy to get to.

#+begin_src emacs-lisp
  (ensure-installed-and-require 'magit)
  (global-set-key "\C-cg" 'magit-status)
#+end_src

   Any git buffer will have magit-auto-revert-mode active; there's no
   need to have both =Git= and =MRev= in the modeline.

#+begin_src emacs-lisp
  (diminish 'magit-auto-revert-mode)
#+end_src

** exec-path-from-shell

   This is a little package that initializes emacs's =exec-path=
   variable from whatever your shell's =$PATH= is.

#+begin_src emacs-lisp
  (ensure-installed-and-require 'exec-path-from-shell)
  (exec-path-from-shell-initialize)
#+end_src

** y-or-n-p

   This replaces dialogs which require a full "yes" or "no" to just
   require a simple "y" or "n".

#+begin_src emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+end_src

** indicate empty lines

    This adds a graphic in the margin to show how many empty lines you
    have beyond the end of your file's content.

#+begin_src emacs-lisp
  (set-default 'indicate-empty-lines t)
#+end_src

** remap windows key ("super") to meta

   On non-OS/X operating systems, I want the windows key on the
   keyboard to be another meta key.

#+begin_src emacs-lisp
  (when (string-equal system-type "gnu/linux")
    (setq x-super-keysym 'meta))
#+end_src

** enable commands

   Emacs has a few commands which are disabled by default, because
   they can be confusing.  Enable them here:

#+begin_src emacs-lisp
  (put 'narrow-to-region 'disabled nil)
  (put 'upcase-region 'disabled nil)
#+end_src

* Lisp
** Clojure

   [[https://github.com/clojure-emacs/cider][cider]] is a package for live-coding Clojure by interacting with a
   Clojure nREPL instance.  [[https://github.com/clojure-emacs/clojure-mode][clojure-mode]] is the major mode for editing
   clojure code.

#+begin_src emacs-lisp
  (ensure-installed-and-require 'cider)
  (ensure-installed-and-require 'clojure-mode)
#+end_src

   Files ending with =.clj= will automatically use clojure-mode, but
   =.cljs= seems to need configuration:

#+begin_src emacs-lisp
  (add-to-list 'auto-mode-alist '("\.cljs$" . clojure-mode))
#+end_src

** Pretty lambdas

   Font-lock stuff to display character sequences such as =lambda= as
   unicode chars such as λ.

   First, we define the font-lock function to detect the appropriate
   sequence and what to replace it with:

#+begin_src emacs-lisp
  (defun pretty-lambdas ()
    (font-lock-add-keywords
     nil `(("\\(\\<lambda\\>\\)"
            (0 (progn (compose-region (match-beginning 1) (match-end 1)
                                      ,(string-to-char "λ"))
                      nil))))))
#+end_src

   Then we add it to some lisp modes:

#+begin_src emacs-lisp
  (add-hook 'clojure-mode-hook #'pretty-lambdas)
  (add-hook 'scheme-mode-hook #'pretty-lambdas)
#+end_src

** Paredit

   Paredit is a minor mode for enforcing balanced parentheses and
   providing operations on sets of parentheses -- generally "slurp"
   and "barf" to swallow or remove terms at the right-hand side of a
   paren pair.  Naturally, this is a good fit for lisps.

   I'm not entirely sure I understand the =autoload= line here.  I
   think I cribbed it from somewhere on the internet.

#+begin_src emacs-lisp
  (ensure-installed-and-require 'paredit)
  (autoload 'enable-paredit-mode "paredit" "Turn on pseudo-structural editing of Lisp code." t)
  (add-hook 'clojure-mode-hook #'enable-paredit-mode)
  (add-hook 'emacs-lisp-mode-hook #'enable-paredit-mode)
  (add-hook 'scheme-mode-hook #'enable-paredit-mode)
#+end_src

* Haskell

** Haskell mode

#+begin_src emacs-lisp
  (add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)
#+end_src

** Pretty arrows

   Font-lock stuff:

   - =->= (used in function types) gets turned into →
   - =<-= (used in do-notation) gets turned into ←
   - =\= gets turned into λ

#+begin_src emacs-lisp
  (defun pretty-arrows ()
    (font-lock-add-keywords
     nil `(("\\(->\\)"
            (0 (progn (compose-region (match-beginning 1) (match-end 1)
                                      (string-to-char "→")))))
           ("\\(<-\\)"
            (0 (progn (compose-region (match-beginning 1) (match-end 1)
                                      (string-to-char "←")))))
           ("\\(\\\\\\)"
            (0 (progn (compose-region (match-beginning 1) (match-end 1)
                                      (string-to-char "λ"))))))))

  (add-hook 'haskell-mode-hook #'pretty-arrows)
#+end_src

* puppet

  [[https://docs.puppetlabs.com/puppet/][Puppet]] is a configuration management language.  First, we want the
  major mode for editing puppet code:

#+begin_src emacs-lisp
  (ensure-installed-and-require 'puppet-mode)
#+end_src

  When we edit =.pp= files, we want to automatically run puppet-mode:

#+begin_src emacs-lisp
  (add-to-list 'auto-mode-alist '("\.pp$" . puppet-mode))
#+end_src

* Markdown

#+begin_src emacs-lisp
  (ensure-installed-and-require 'markdown-mode)
#+end_src

* org mode

** capture

   Org mode supports a feature called "[[http://orgmode.org/manual/Capture.html][capture]]", which allows you to
   quickly capture TODO items while working on something else.  This
   needs a global key combination (=C-c c=) to capture notes.

   We also need to tell org which file captured notes should be added
   to.

#+begin_src emacs-lisp
  (global-set-key "\C-cc" 'org-capture)
  (setq org-default-notes-file (concat org-directory "/todo.org"))
#+end_src

** other global keys

#+begin_src emacs-lisp
  (global-set-key "\C-cl" 'org-store-link)
  (global-set-key "\C-ca" 'org-agenda)
  (global-set-key "\C-cb" 'org-iswitchb)
#+end_src

** export options

   I use org-reveal to generate presentations with org-mode.  Normally
   org-mode will helpfully generate a table of contents on html
   export, but this isn't great for a reveal presentation, so let's
   disable it:

#+begin_src emacs-lisp
  (setq org-export-with-toc nil)
#+end_src

** org-babel

   [[http://orgmode.org/worg/org-contrib/babel/][Babel]] is org-mode's ability to execute source code within
   documents.  (It's how this config file gets run.)

   To avoid running arbitrary code, each specific language that you
   want to allow org-mode to run code for on export needs to be
   enabled here:

#+begin_src emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((clojure . t)
     (ditaa . t)
     (python . t)
     (ruby . t)
     ))
#+end_src

   (ditaa is a language for drawing diagrams in ascii art and
   generating graphical output.  org-mode has builtin support for
   ditaa.)

   We want to fontify code in code blocks:

#+begin_src emacs-lisp
  (setq org-src-fontify-natively t)
#+end_src

* twitter

  Emacs's twittering-mode provides a twitter client.  This sets up the
  default timelines that will be opened when I launch twittering-mode:

#+begin_src emacs-lisp
  (setq twittering-initial-timeline-spec-string
        '(":home" ":replies"))
#+end_src

* rcirc

  rcirc is an irc client from within emacs.  Most of my settings are
  in my [[secrets]] file, as they contain passwords.

** rcirc-track

   The rcirc-track-minor-mode is a global minor mode which adds an
   indicator to the modeline indicating which irc buffers have had
   activity, and also which buffers have mentioned you by nick:

#+begin_src emacs-lisp
  (rcirc-track-minor-mode 1)
#+end_src

** omit

   Don't show JOIN and PART messages by default, except for people
   with recent activity.  (This is the behaviour you get with =C-c
   C-o= but I want it on by default.)  Also, don't show
   rcirc-omit-mode in the modeline.

#+begin_src emacs-lisp
  (add-hook 'rcirc-mode-hook 'rcirc-omit-mode)
  (diminish 'rcirc-omit-mode)
#+end_src

* local settings
  This repo has a /local directory, with all of its contents in
  =.gitignore=, containing various local settings.

** customized variables
   custom.el provides a mechanism for customizing emacs variables from
   within emacs.  To make such changes permanent, it will put changes
   into =custom-file= which by default is =init.el=.  To avoid
   polluting that file, we set it to something else:

   #+BEGIN_SRC emacs-lisp
     (setq custom-file (concat user-emacs-directory "custom.el"))
     (load custom-file 'noerror)
   #+END_SRC

** secrets

   It is good to store your passwords and things in an encrypted
   file.

   This does mean that every time you use it you have to give the
   passphrase, but it does mean that you can keep all your passwords
   for things like rcirc and stuff in a file reasonably safely (though
   it will be in memory when emacs is running, so it isn't completely
   secure).

   #+BEGIN_SRC emacs-lisp
     (load (concat user-emacs-directory "local/secrets.el.gpg") 'noerror)
   #+END_SRC

